services:
  database:
    container_name: "postgres-dev"
    image: "postgres:16-alpine3.18"
    env_file:
      - ../.env.development # Carrega variáveis do arquivo .env localizado no diretório pai
    ports:
      - "5432:5432"
